#!/usr/bin/env sh

DEV=debian-12
BR=br0

down() {
	ip tuntap del name $DEV mode tap
}

panic() {
	down && exit $1
}

up() {
	ip tuntap add name $DEV mode tap || panic 1
	ip link set dev $DEV up || panic 1

	ip link set dev $DEV master $BR || panic 1
}

$@
exit $?
